name: Build Ubuntu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          . ci/install_ubuntu.sh
          . build_linux.sh
        env:
          OBS_VER: 27.1.3
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: obs-multi-rtmp
          path: dist